# Generated by Django 4.1 on 2022-10-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default='', upload_to='main/static/main/images'),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='number',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
