# Generated by Django 4.1 on 2022-10-11 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_productinorder_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productinorder',
            name='number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='productinorder',
            name='price_per_item',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
