# Generated by Django 4.1 on 2022-10-31 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_order_is_active_product_is_new_productimage_is_main_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
