# Generated by Django 4.1 on 2022-10-31 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_product_discount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='number',
        ),
    ]
