# Generated by Django 4.1 on 2022-12-04 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_productincart'),
    ]

    operations = [
        migrations.AddField(
            model_name='productincart',
            name='session_key',
            field=models.CharField(default='', max_length=128),
        ),
    ]
