# Generated by Django 4.1 on 2023-02-03 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_productincart_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productincart',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.order'),
        ),
    ]
